version: '3.8'

services:
  frontend:
    build:
      context: ./find-jeja-fe
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - /root/nginx.key:/etc/nginx/certs/nginx.key:ro
      - /root/nginx.crt:/etc/nginx/certs/nginx.crt:ro
    networks:
      - find-jeja-net

  backend:
    build:
      context: ./find-jeja-be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/find-jeja
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - find-jeja-net

  db:
    image: mysql:8.0
    container_name: find-jeja-db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: find-jeja
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./find-jeja-be/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./find-jeja-be/src/main/resources/insert_data.sql:/docker-entrypoint-initdb.d/insert_data.sql:ro
    ports:
      - "3306:3306"
    networks:
      - find-jeja-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  find-jeja-net:
    driver: bridge

volumes:
  mysql_data:
