version: '3.8'

services:
  frontend:
    build:
      context: ./find-jeja-fe
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/nginx.key:/etc/nginx/certs/nginx.key:ro
      - /root/nginx.crt:/etc/nginx/certs/nginx.crt:ro
    networks:
      - find-jeja-net

  backend-v2:
    build:
      context: ./find-jeja-be-v2/app
      dockerfile: ../Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/hint_game_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy
    networks:
      - find-jeja-net

  db:
    image: mysql:8.0
    container_name: find-jeja-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hint_game_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - find-jeja-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  find-jeja-net:
    driver: bridge

volumes:
  mysql_data: