name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy with Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no -T -p 49088 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} /bin/bash << 'EOF'
          set -ex
          
          echo "Navigating to the project directory..."
          cd /root/find-jeja
          
          echo "Pulling the latest changes from the main branch..."
          git pull origin main
          
          echo "Bringing down the existing Docker containers..."
          docker compose down
          
          echo "Building and starting the new Docker containers in detached mode..."
          docker compose up --build -d
          
          echo "Deployment to CentOS server completed successfully!"
        EOF
